In [84]:
import pandas as pd
import json
import numpy
import csv
import requests

In [85]:
# Import csv

file_to_load = "large_cities.csv"
city_data = pd.read_csv(file_to_load)
city_data

    Unnamed: 0               city state  population        lng        lat
0        16831          Anchorage    AK    298695.0   298695.0   298695.0
1        16832         Birmingham    AL    212461.0   212461.0   212461.0
2        16833        Little Rock    AR    197992.0   197992.0   197992.0
3        16834            Phoenix    AZ   1563025.0  1563025.0  1563025.0
4        16835        Los Angeles    CA   3971883.0  3971883.0  3971883.0
5        16836             Denver    CO    682545.0   682545.0   682545.0
6        16837         Bridgeport    CT    147629.0   147629.0   147629.0
7        16838         Washington    DC    601723.0   601723.0   601723.0
8        16839         Wilmington    DE     71948.0    71948.0    71948.0
9        16840       Jacksonville    FL    868031.0   868031.0   868031.0
10       16841            Atlanta    GA    463878.0   463878.0   463878.0
11       16842           Honolulu    HI    371657.0   371657.0   371657.0
12       16843         Des Moines    IA    210330.0   210330.0   210330.0
13       16844              Boise    ID    145987.0   145987.0   145987.0
14       16845            Chicago    IL   2720546.0  2720546.0  2720546.0
15       16846       Indianapolis    IN    829718.0   829718.0   829718.0
16       16847            Wichita    KS    389965.0   389965.0   389965.0
17       16848  Lexington-Fayette    KY    314488.0   314488.0   314488.0
18       16849        New Orleans    LA    389617.0   389617.0   389617.0
19       16850             Boston    MA    667137.0   667137.0   667137.0
20       16851          Baltimore    MD    621849.0   621849.0   621849.0
21       16852           Portland    ME     66881.0    66881.0    66881.0
22       16853            Detroit    MI    677116.0   677116.0   677116.0
23       16854        Minneapolis    MN    410939.0   410939.0   410939.0
24       16855        Kansas City    MO    475378.0   475378.0   475378.0
25       16856            Jackson    MS    170674.0   170674.0   170674.0
26       16857           Billings    MT    110263.0   110263.0   110263.0
27       16858          Charlotte    NC    827097.0   827097.0   827097.0
28       16859              Fargo    ND    118523.0   118523.0   118523.0
29       16860              Omaha    NE    443885.0   443885.0   443885.0
30       16861         Manchester    NH    110229.0   110229.0   110229.0
31       16862             Newark    NJ    281944.0   281944.0   281944.0
32       16863        Albuquerque    NM    559121.0   559121.0   559121.0
33       16864          Las Vegas    NV    623747.0   623747.0   623747.0
34       16865      New York City    NY   8175133.0  8175133.0  8175133.0
35       16866           Columbus    OH    850106.0   850106.0   850106.0
36       16867      Oklahoma City    OK    631346.0   631346.0   631346.0
37       16868           Portland    OR    632309.0   632309.0   632309.0
38       16869       Philadelphia    PA   1567442.0  1567442.0  1567442.0
39       16870         Providence    RI    179207.0   179207.0   179207.0
40       16871           Columbia    SC    133803.0   133803.0   133803.0
41       16872        Sioux Falls    SD    171544.0   171544.0   171544.0
42       16873            Memphis    TN    655770.0   655770.0   655770.0
43       16874            Houston    TX   2296224.0  2296224.0  2296224.0
44       16875     Salt Lake City    UT    192672.0   192672.0   192672.0
45       16876     Virginia Beach    VA    452745.0   452745.0   452745.0
46       16877         Burlington    VT     42452.0    42452.0    42452.0
47       16878            Seattle    WA    684451.0   684451.0   684451.0
48       16879          Milwaukee    WI    600155.0   600155.0   600155.0
49       16880         Charleston    WV     49736.0    49736.0    49736.0
50       16881           Cheyenne    WY     63335.0    63335.0    63335.0

In [86]:
city_data2 = city_data['city'].str.replace(' ', '%20')
city_data2 = city_data2.str.lower()
# city_data2

In [87]:
# city_url = "https://api.teleport.org/api/cities/?search="
# city_url
# city2_url =

In [88]:
# city2 = city_data2
# # Build query URL
# query_url = city_url + city2
# query_url[0]

In [89]:
# response = requests.get(query_url[0])
# qof_json = response.json()
# qof_json

In [90]:
city_data3 = city_data['city'].str.replace(' ', '-')
city_data3 = city_data3.str.lower()
city3 = city_data3
city3

0             anchorage
1            birmingham
2           little-rock
3               phoenix
4           los-angeles
5                denver
6            bridgeport
7            washington
8            wilmington
9          jacksonville
10              atlanta
11             honolulu
12           des-moines
13                boise
14              chicago
15         indianapolis
16              wichita
17    lexington-fayette
18          new-orleans
19               boston
20            baltimore
21             portland
22              detroit
23          minneapolis
24          kansas-city
25              jackson
26             billings
27            charlotte
28                fargo
29                omaha
30           manchester
31               newark
32          albuquerque
33            las-vegas
34        new-york-city
35             columbus
36        oklahoma-city
37             portland
38         philadelphia
39           providence
40             columbia
41          sioux-falls
42              memphis
43              houston
44       salt-lake-city
45       virginia-beach
46           burlington
47              seattle
48            milwaukee
49           charleston
50             cheyenne
Name: city, dtype: object

In [91]:
query2_url ='https://api.teleport.org/api/urban_areas/slug:' + city3 + '/scores/'
query2_url
response2 = requests.get(query2_url)
qof2_json = response2.json()
qof2_json

InvalidSchema: No connection adapters were found for '0     https://api.teleport.org/api/urban_areas/slug:...\n1     https://api.teleport.org/api/urban_areas/slug:...\n2     https://api.teleport.org/api/urban_areas/slug:...\n3     https://api.teleport.org/api/urban_areas/slug:...\n4     https://api.teleport.org/api/urban_areas/slug:...\n5     https://api.teleport.org/api/urban_areas/slug:...\n6     https://api.teleport.org/api/urban_areas/slug:...\n7     https://api.teleport.org/api/urban_areas/slug:...\n8     https://api.teleport.org/api/urban_areas/slug:...\n9     https://api.teleport.org/api/urban_areas/slug:...\n10    https://api.teleport.org/api/urban_areas/slug:...\n11    https://api.teleport.org/api/urban_areas/slug:...\n12    https://api.teleport.org/api/urban_areas/slug:...\n13    https://api.teleport.org/api/urban_areas/slug:...\n14    https://api.teleport.org/api/urban_areas/slug:...\n15    https://api.teleport.org/api/urban_areas/slug:...\n16    https://api.teleport.org/api/urban_areas/slug:...\n17    https://api.teleport.org/api/urban_areas/slug:...\n18    https://api.teleport.org/api/urban_areas/slug:...\n19    https://api.teleport.org/api/urban_areas/slug:...\n20    https://api.teleport.org/api/urban_areas/slug:...\n21    https://api.teleport.org/api/urban_areas/slug:...\n22    https://api.teleport.org/api/urban_areas/slug:...\n23    https://api.teleport.org/api/urban_areas/slug:...\n24    https://api.teleport.org/api/urban_areas/slug:...\n25    https://api.teleport.org/api/urban_areas/slug:...\n26    https://api.teleport.org/api/urban_areas/slug:...\n27    https://api.teleport.org/api/urban_areas/slug:...\n28    https://api.teleport.org/api/urban_areas/slug:...\n29    https://api.teleport.org/api/urban_areas/slug:...\n30    https://api.teleport.org/api/urban_areas/slug:...\n31    https://api.teleport.org/api/urban_areas/slug:...\n32    https://api.teleport.org/api/urban_areas/slug:...\n33    https://api.teleport.org/api/urban_areas/slug:...\n34    https://api.teleport.org/api/urban_areas/slug:...\n35    https://api.teleport.org/api/urban_areas/slug:...\n36    https://api.teleport.org/api/urban_areas/slug:...\n37    https://api.teleport.org/api/urban_areas/slug:...\n38    https://api.teleport.org/api/urban_areas/slug:...\n39    https://api.teleport.org/api/urban_areas/slug:...\n40    https://api.teleport.org/api/urban_areas/slug:...\n41    https://api.teleport.org/api/urban_areas/slug:...\n42    https://api.teleport.org/api/urban_areas/slug:...\n43    https://api.teleport.org/api/urban_areas/slug:...\n44    https://api.teleport.org/api/urban_areas/slug:...\n45    https://api.teleport.org/api/urban_areas/slug:...\n46    https://api.teleport.org/api/urban_areas/slug:...\n47    https://api.teleport.org/api/urban_areas/slug:...\n48    https://api.teleport.org/api/urban_areas/slug:...\n49    https://api.teleport.org/api/urban_areas/slug:...\n50    https://api.teleport.org/api/urban_areas/slug:...\nName: city, dtype: object'

In [92]:
x = (city_data['city'][0], 
    qof2_json['categories'][0]['name'], 
     qof2_json['categories'][0]['score_out_of_10'],
     qof2_json['categories'][1]['name'],
     qof2_json['categories'][1]['score_out_of_10'],
     qof2_json['categories'][4]['name'],
     qof2_json['categories'][4]['score_out_of_10'],
     qof2_json['categories'][5]['name'],
     qof2_json['categories'][5]['score_out_of_10'],
     qof2_json['categories'][9]['name'],
     qof2_json['categories'][9]['score_out_of_10'],
     qof2_json['summary'])

x

('Anchorage',
 'Housing',
 5.433500000000001,
 'Cost of Living',
 3.141,
 'Travel Connectivity',
 1.7379999999999998,
 'Commute',
 4.715249999999999,
 'Education',
 3.6245,
 '<p>Anchorage, Alaska, is characterized by a <b>clean environment</b>.\n\n    \n        According to our city rankings, this is a good place to live with high ratings in <b>business freedom</b>, <b>healthcare</b> and <b>tolerance</b>.\n    \n\n    \n</p>\n\n')

In [93]:
qol_df = pd.DataFrame()
index = 0

for dictionary in qof2_json:
    qof2_json.loc[index,'Subject'] = dictionary['categories']['name']
    qof2_json.loc[index,'Score out of 10'] = dictionary['categories']['score_out_of_10']
    qof2_json.loc[index,"Summary"] = dictionary['summary']

    index+=1

qof2_json

TypeError: string indices must be integers

In [94]:
cities = city_data['city'].to_list()
cities

['Anchorage',
 'Birmingham',
 'Little Rock',
 'Phoenix',
 'Los Angeles',
 'Denver',
 'Bridgeport',
 'Washington',
 'Wilmington',
 'Jacksonville',
 'Atlanta',
 'Honolulu',
 'Des Moines',
 'Boise',
 'Chicago',
 'Indianapolis',
 'Wichita',
 'Lexington-Fayette',
 'New Orleans',
 'Boston',
 'Baltimore',
 'Portland',
 'Detroit',
 'Minneapolis',
 'Kansas City',
 'Jackson',
 'Billings',
 'Charlotte',
 'Fargo',
 'Omaha',
 'Manchester',
 'Newark',
 'Albuquerque',
 'Las Vegas',
 'New York City',
 'Columbus',
 'Oklahoma City',
 'Portland',
 'Philadelphia',
 'Providence',
 'Columbia',
 'Sioux Falls',
 'Memphis',
 'Houston',
 'Salt Lake City',
 'Virginia Beach',
 'Burlington',
 'Seattle',
 'Milwaukee',
 'Charleston',
 'Cheyenne']

In [96]:
city = []
subject = []
score = []
summary = []

index = 0

for city in cities:

    try:
        city.append(city_data['city'])
        subject.append(qof2_json['categories']['name'])
        score.append(qof2_json['categories']['score_out_of_10'])
        sumamry.append(qof2_json['summary'])

        print(f"Data found for city number: {index}, city name: {qof2_json['categories']['name']}")
    
        index+=1
    
    except:
        print(f"City data for {index} {qof2_json['categories']['name']} not found. Move on to next.")
        index+=1

TypeError: list indices must be integers or slices, not str